name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.0.X'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration ${{ matrix.configuration }}

      - name: Test
        run: dotnet test --no-build --configuration ${{ matrix.configuration }} /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura

      - name: Report Coveralls (Linux)
        #if: startsWith(runner.os, 'Linux')
        run: |
          curl -sL https://coveralls.io/coveralls-linux.tar.gz | tar -xz
          ./coveralls report TestResults/SimplCommerce.Module.Pricing.Tests.coverage.cobertura.xml --no-logo
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.Coveralls_Repo_Token }}
